services:
  backend:
    build:
      context: ./
      args:
        NEW_RELIC_API_KEY: $NEW_RELIC_API_KEY
        NEW_RELIC_ACCOUNT_ID: $NEW_RELIC_ACCOUNT_ID
        NEW_RELIC_REGION: $NEW_RELIC_REGION
        NEW_RELIC_APP_NAME: $NEW_RELIC_APP_NAME
        NEW_RELIC_LICENSE_KEY: $NEW_RELIC_LICENSE_KEY
    environment:
      NEW_RELIC_API_KEY: $NEW_RELIC_API_KEY
      NEW_RELIC_ACCOUNT_ID: $NEW_RELIC_ACCOUNT_ID
      NEW_RELIC_REGION: $NEW_RELIC_REGION
      NEW_RELIC_APP_NAME: $NEW_RELIC_APP_NAME
      NEW_RELIC_LICENSE_KEY: $NEW_RELIC_LICENSE_KEY
    volumes:
      - ./src:/var/www/tp-performances
      - ./docker/nginx.conf:/etc/nginx/sites-available/tp-performances
      - ./docker/php.ini:/etc/php/8.1/fpm/php.ini
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: "mariadb:latest"
    ports:
      - 3306:3306
    volumes:
      - ./docker/volumes/db/:/var/lib/mysql
    environment:
      MARIADB_DATABASE: "tp"
      MARIADB_ROOT_PASSWORD: "root"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 300M
    depends_on:
      - db

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./docker/volumes/redis:/data

  reviews-api:
    hostname: cheap-trusted-reviews.fake
    build:
      context: api/
    ports:
      - 8888:80
    environment:
      DB_HOST: "db"
      DB_USER: "root"
      DB_PASS: "root"
      DB_NAME: "tp"
    depends_on:
      - db